# Generated by Django 3.1.2 on 2020-10-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='short_summary',
            field=models.CharField(default='Add Summary Here', max_length=50),
        ),
    ]
