# Generated by Django 3.1.2 on 2020-10-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_short_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='short_summary',
            new_name='Short Summary',
        ),
    ]
